
PLC_CHANNEL CHANNEL {
	OPTION host "localhost";
	OPTION port 7701;
	MONITORS MACHINES LINKED TO CORE_MASTER;
	MONITORS MACHINES LINKED TO GRAB_MASTER;
	MONITORS MACHINES LINKED TO GRAB_CUTTER;
	PUBLISHER;
}

