
SIMPLEFOLLOWER MACHINE other {
	interlocked WHEN other DISABLED;
	error WHEN SELF IS NOT other.STATE AND TIMER>10 AND other.TIMER>10;
	on WHEN SELF IS on;
	off WHEN SELF IS off;
	on WHEN other IS on;
	off WHEN other IS off;
	error DEFAULT;
}
a SIMPLEFOLLOWER b;
b SIMPLEFOLLOWER a;

CHANNELMONITORINTERFACE INTERFACE{
	interlocked INITIAL;
	on STATE;
	off STATE;
}


DELAYEDFOLLOWER MACHINE a { 
on WHEN a IS on AND a.TIMER >=1000, EXECUTE goOff WHEN a IS off AND a.TIMER>=1000;
on DEFAULT;
COMMAND goOff { SET SELF TO off; }
}

DELAYEDINVERTER MACHINE a {
off WHEN a IS on AND a.TIMER >=1000, EXECUTE goOn WHEN a IS off AND a.TIMER>=1000;
on DEFAULT;
COMMAND goOn { SET SELF TO on; }
}

#a DELAYEDFOLLOWER b;
#b DELAYEDINVERTER a;

