MODBUSMODULE MACHINE {
	OPTION host "localhost";
	OPTION port 1502;
}

OUTPUTBIT MACHINE PLC {
	OPTION COIL "Y0";
	off INITIAL;
	on STATE;

	RECEIVE turnOn { SET SELF TO on; }
	RECEIVE turnOff { SET SELF TO off; }
	RECEIVE TOGGLE { CALL next ON SELF; }
	COMMAND next {}
	TRANSITION on TO off ON next;
	TRANSITION off TO on ON next;
}

INPUTBIT MACHINE PLC {
	OPTION INPUT "X0";
	off INITIAL;
	on STATE;
}

INPUTREGISTER MACHINE PLC {
	OPTION REGISTER "V0";
	OPTION VALUE 0;
}

OUTPUTREGISTER MACHINE PLC {
	OPTION HOLDING "W0";
	OPTION VALUE 0;
}

PLC_MONITOR CHANNEL {
	OPTION host "localhost";
	OPTION port 7701;
	MONITORS MACHINES LINKED TO PLC;
	PUBLISHER;
}

