// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef grab_console_h
#define grab_console_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

class GrabUserInterface {
public:
  Fl_Double_Window* make_window();
};
#endif
