// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef loader_panel_h
#define loader_panel_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Light_Button.H>
extern void press(Fl_Light_Button*, void*);
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Input.H>
extern void save(Fl_Value_Input*, void*);
extern void set_auto_mode(Fl_Light_Button*, void*);

class LoaderPanel {
public:
  Fl_Double_Window* make_window();
};
#endif
