// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef loader_panel_h
#define loader_panel_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Light_Button.H>
extern void press(Fl_Light_Button*, void*);
#include <FL/Fl_Box.H>

class LoaderPanel {
public:
  Fl_Double_Window* make_window();
};
#endif
