#!/bin/sh
#
# Backup a Clockwork persist.dat on a regular basis (e.g. cron).
#
# Set PERSISTFILE to your site's persist path. There is no generic product
# default under a plant `code/` tree.
#
# to prepare:
# mkdir $BACKUPDIR && cd $BACKUPDIR && git init && cp "$PERSISTFILE" . && git add "`basename $PERSISTFILE`"

[ "$BACKUPDIR" = "" ] && BACKUPDIR=/root/settings
if [ "$PERSISTFILE" = "" ]; then
	echo "backup_persist: set PERSISTFILE to your site persist.dat path" >&2
	exit 1
fi

cd $BACKUPDIR || exit 2
cp $PERSISTFILE .
date >>/tmp/backup_persist.log 2>&1
git commit -m "`date`" "$(basename "$PERSISTFILE")" >>/tmp/backup_persist.log 2>&1
