%{
#include <stdlib.h>
#include "cmdline.h"
#include "cmdline.tab.hpp"
#ifdef USE_READLINE
#include <readline/readline.h>
#include <readline/history.h>
#endif

void yyerror(const char *);
static char *buf;
static int buflen = 0;
static char *bufp;
extern YYSTYPE yylval;
int yycharno;
static char json_delim;
static int json_depth;

extern bool cmdline_done;

void append_char(int ch);
void prepare_buffer();
void begin_group(char start);
int end_group(char end);

%}
%x STRING
%x COMMENT
%x JSONSTR
%x JSONEXPRSTR

%%

JSON_VALUE        {
                    BEGIN JSONSTR;
                    json_delim = 0;
                    json_depth = 0;
                    prepare_buffer();
                  }
<JSONSTR>" "      {   if (json_delim != 0) { append_char(*yytext); } }
<JSONSTR>"{"      {
                    if (json_delim == 0) { json_delim = '{'; }
                    begin_group('{');
                  }
<JSONSTR>"}"      { if (end_group('}') == 0) { return JSONVAL; } }
<JSONSTR>"["      {
                    if (json_delim == 0) { json_delim = '['; }
                    begin_group('[');
                  }
<JSONSTR>"]"      { if (end_group(']') == 0) { return JSONVAL; } }
<JSONSTR>\n       { append_char(*yytext); yylineno++; yycharno=1; }
<JSONSTR>.        {
                    if (json_delim == 0) {
                      printf("invalid JSON character %d (%c)\n", *yytext, *yytext);
                      yyerror("Unexpected character");
                    }
                    else {
                      append_char(*yytext);
                    }
                  }

"${"              { BEGIN JSONEXPRSTR; prepare_buffer(); }
<JSONEXPRSTR>\n   { append_char('\n'); yylineno++; yycharno=1; }
<JSONEXPRSTR>"}"  {
                      BEGIN 0;
                      yylval.jsExpr = buf;
                      buf = NULL;
                      return JSONEXPR;
                  }
<JSONEXPRSTR>.    { append_char(*yytext); }

JSON               return JSON;


[A-Za-z][A-Za-z0-9_.:]*       {
    yylval.sVal = strdup(yytext);
    return SYMBOL;
}

"0x"[0-9a-fA-F][0-9a-fA-F]* {
	long val;
	char *p;
	val = strtol(yytext, &p, 16);
	yylval.iVal = val;
	return INTEGER;
}

[-]{0,1}([0-9][0-9]*){0,1}[.][0-9]*([eE][-]{0,1}[0-9]{1,3}){0,1} {
	yylval.fVal = atof(yytext);
	//std::cout << "FLOAT: " << yytext << ": " << yylval.fVal << "\n";
	return FLOAT;
}

0           {
	yylval.iVal = atoi(yytext);
	return INTEGER;
}

[-]{0,1}[0-9][0-9]* {
	long val;
	char *p;
	val = strtol(yytext, &p, 10);
	yylval.iVal = val;
	return INTEGER;
}

\"  {  /*"*/	
	BEGIN STRING; 
		if (!buf) 
		{ 
			buf = (char *)malloc(20); 
			buflen = 20; 
		}
		bufp = buf;
		*bufp = 0;
 		}
<STRING>\\n		{ append_char('\n'); }
<STRING>\\r		{ append_char('\r'); }
<STRING>\\t		{ append_char('\t'); }
<STRING>\\[0-3][0-7][0-7] { unsigned char ch = ((yytext[1]-'0')*8 + yytext[2]-'0')*8+yytext[3]-'0'; append_char(ch); }
<STRING>\\\"	{ /*"*/ append_char('\"'); }
<STRING>\"		{ /*"*/ BEGIN 0; yylval.sVal = buf; buf = NULL; return STRINGVAL; }
<STRING>\n		{ append_char('\n'); yylineno++; yycharno=1; }
<STRING>.		{ append_char(*yytext); }

[ \t]+        ;       /* ignore whitespace */

\'              /*' ignore single quotes */

['()=+*/;{}.%] {
    return *yytext;
}

.               { printf("found char %d (%c)\n", *yytext, *yytext); yyerror("Unknown character"); } 

%%

int yywrap(void) {
    return 1;
}

void append_char(int ch)
{
	if (bufp - buf == buflen-1) {
		buf = (char *)realloc(buf, buflen + 20);
		bufp = buf + buflen-1;
		buflen += 20;
	}
	*bufp++ = ch;
	*bufp = 0;
}

void prepare_buffer() {
    if (!buf)
    {
        buf = (char *)malloc(20);
        buflen = 20;
    }
        bufp = buf;
    *bufp = 0;
}

void begin_group(char start) {
    append_char(start);
    if (json_delim == start) {
        json_depth++;
    }
}

int end_group(char end) {
    append_char(end);
    if ((json_delim == '{' && end == '}') || (json_delim == '[' && end == ']')) {
        if (--json_depth == 0) {
            BEGIN 0;
            printf("JSON: %s\n", buf);
            yylval.jVal = cJSON_Parse(buf);
            buf = NULL;
        }
    }
    return json_depth;
}

int get_input(char *buf, unsigned int size)
{
    char *line;
    static char *last_read = (char *)NULL;
    if (feof(yyin)) { return YY_NULL; }
    line = readline("> ");
    if (!line) {
		cmdline_done = true;
    	return YY_NULL;
	}
    if (strlen(line) > size - 2) {
        yyerror("input line too long");
        return YY_NULL;
    }
    strcpy(buf, line);
    free(line);
    
    if (strlen(buf)) {
        if (last_read && strcmp(buf, last_read) != 0) {
            free(last_read);
            last_read = 0;
        }
        if (!last_read) {
            add_history (buf);
            last_read = strdup(buf);
        }
    }
    return static_cast<int>(strlen(buf));
}

