/*
    Generate <Class>INTERFACE Clockwork from RECORD classes.
    Persist COMMANDs live on the generated MACHINE, not on the RECORD.
*/

#include "Dispatcher.h"
#include "Logger.h"
#include "MachineClass.h"
#include "MessageLog.h"
#include "MessagingInterface.h"
#include "Scheduler.h"
#include "ThreadSafeQueue.h"
#include "clockwork.h"
#include "options.h"
#include "symboltable.h"
#include "value.h"
#include <Statistic.h>
#include <Statistics.h>
#include <boost/thread/mutex.hpp>
#include <boost/filesystem.hpp>
#include <fstream>
#include <iostream>
#include <libgen.h>
#include <list>
#include <sstream>
#include <string.h>
#include <string>
#include <vector>
#include <zmq.hpp>

bool program_done = false;
bool machine_is_ready = false;
Statistics *statistics = NULL;
std::list<Statistic *> Statistic::stats;

namespace {

std::string json_escape(const std::string &s) {
    std::string out;
    out.reserve(s.size());
    for (size_t i = 0; i < s.size(); ++i) {
        char c = s[i];
        if (c == '\\' || c == '"') {
            out.push_back('\\');
        }
        out.push_back(c);
    }
    return out;
}

std::string json_literal(const Value &v) {
    if (v.isNull() || v.kind == Value::t_empty) {
        return "null";
    }
    if (v.kind == Value::t_integer || v.kind == Value::t_float) {
        return v.asString();
    }
    if (v.kind == Value::t_bool) {
        bool b = false;
        v.asBoolean(b);
        return b ? "true" : "false";
    }
    return std::string("\"") + json_escape(v.asString()) + "\"";
}

struct Column {
    std::string name;
    Value default_value;
    unsigned flags;
};

void collect_columns(const MachineClass *mc, std::vector<Column> &cols, std::vector<Column> &keys) {
    const std::map<std::string, Value> &opts = mc->getOptions();
    std::map<std::string, Value>::const_iterator it = opts.begin();
    while (it != opts.end()) {
        const std::string &name = it->first;
        if (!mc->propertyIsLocal(name)) {
            Column c;
            c.name = name;
            c.default_value = it->second;
            c.flags = mc->getColumnFlags(name);
            if (c.flags & MachineClass::COL_KEY) {
                keys.push_back(c);
            }
            cols.push_back(c);
        }
        ++it;
    }
}

void emit_object_fields(std::ostream &out, const std::vector<Column> &cols) {
    const char *sep = "";
    for (size_t i = 0; i < cols.size(); ++i) {
        out << sep << "\"" << cols[i].name << "\": " << json_literal(cols[i].default_value);
        sep = ", ";
    }
}

void emit_field_list(std::ostream &out, const std::vector<Column> &cols) {
    const char *sep = "";
    for (size_t i = 0; i < cols.size(); ++i) {
        out << sep << "\"" << cols[i].name << "\"";
        sep = ", ";
    }
}

void emit_copies(std::ostream &out, const char *indent, const char *prefix,
                 const std::vector<Column> &cols) {
    for (size_t i = 0; i < cols.size(); ++i) {
        out << indent << "ITEM ${" << prefix << "." << cols[i].name << "} OF request := record."
            << cols[i].name << ";\n";
    }
}

const char *sql_type(const Value &v) {
    if (v.kind == Value::t_integer || v.kind == Value::t_bool) {
        return "INTEGER";
    }
    if (v.kind == Value::t_float) {
        return "REAL";
    }
    return "TEXT";
}

std::string sql_default(const Value &v) {
    if (v.kind == Value::t_empty || v.isNull()) {
        return "";
    }
    if (v.kind == Value::t_integer || v.kind == Value::t_float) {
        return v.asString();
    }
    if (v.kind == Value::t_bool) {
        bool b = false;
        v.asBoolean(b);
        return b ? "1" : "0";
    }
    std::string s = v.asString();
    std::string q = "'";
    for (size_t i = 0; i < s.size(); ++i) {
        if (s[i] == '\'') {
            q += "''";
        }
        else {
            q += s[i];
        }
    }
    q += "'";
    return q;
}

void emit_sql(std::ostream &out, const MachineClass *mc) {
    std::vector<Column> cols;
    std::vector<Column> keys;
    collect_columns(mc, cols, keys);
    const std::string type = mc->table_name.empty() ? mc->name : mc->table_name;
    out << "-- generated by cw-scaffold from RECORD " << mc->name << "\n";
    if (mc->is_view) {
        out << "-- VIEW \"" << type << "\": write CREATE VIEW SQL by hand; "
            << "joins are not inferred from OPTIONS.\n";
        return;
    }
    out << "CREATE TABLE " << type << " (\n";
    for (size_t i = 0; i < cols.size(); ++i) {
        const Column &c = cols[i];
        out << "  " << c.name << " " << sql_type(c.default_value);
        if (c.flags & MachineClass::COL_KEY) {
            out << " PRIMARY KEY";
        }
        else {
            if (c.flags & MachineClass::COL_NOT_NULL) {
                out << " NOT NULL";
            }
            if (c.flags & MachineClass::COL_UNIQUE) {
                out << " UNIQUE";
            }
            std::string def = sql_default(c.default_value);
            if (!def.empty()) {
                out << " DEFAULT " << def;
            }
        }
        if (i + 1 < cols.size()) {
            out << ",";
        }
        out << "\n";
    }
    out << ");\n";
}

void emit_interface(std::ostream &out, const MachineClass *mc) {
    std::vector<Column> cols;
    std::vector<Column> keys;
    collect_columns(mc, cols, keys);
    const std::string type = mc->table_name.empty() ? mc->name : mc->table_name;
    const std::string iface = mc->name + "INTERFACE";
    const bool writes = !mc->is_view;

    out << "# generated by cw-scaffold — do not edit by hand\n";
    out << iface << " MACHINE record, items {\n";
    out << "    OPTION request JSON_VALUE {};\n";

    if (writes) {
        out << "    OPTION insert_template JSON_VALUE {\n";
        out << "        \"action\": \"insert\", \"type\": \"" << type
            << "\", \"auth\": \"xxx\", \"data\": {";
        emit_object_fields(out, cols);
        out << "}\n    };\n";
        out << "    OPTION update_template JSON_VALUE {\n";
        out << "        \"action\": \"update\", \"type\": \"" << type
            << "\", \"auth\": \"xxx\", \"keys\": {";
        emit_object_fields(out, keys);
        out << "}, \"data\": {";
        emit_object_fields(out, cols);
        out << "}\n    };\n";
        out << "    OPTION delete_template JSON_VALUE {\n";
        out << "        \"action\": \"delete\", \"type\": \"" << type
            << "\", \"auth\": \"xxx\", \"keys\": {";
        emit_object_fields(out, keys);
        out << "}\n    };\n";
    }

    out << "    OPTION find_template JSON_VALUE {\n";
    out << "        \"action\": \"find\", \"type\": \"" << type
        << "\", \"auth\": \"xxx\", \"keys\": {";
    emit_object_fields(out, keys);
    out << "}, \"fields\": [";
    emit_field_list(out, cols);
    out << "]\n    };\n";
    out << "    OPTION list_template JSON_VALUE {\n";
    out << "        \"action\": \"find\", \"type\": \"" << type
        << "\", \"auth\": \"xxx\", \"keys\": {}, \"fields\": [";
    emit_field_list(out, cols);
    out << "]\n    };\n";

    if (writes) {
        out << "    COMMAND create {\n";
        out << "        request := insert_template;\n";
        emit_copies(out, "        ", "data", cols);
        out << "        SEND request TO DATABASE_CHANNEL;\n";
        out << "    }\n";
        out << "    COMMAND update {\n";
        out << "        request := update_template;\n";
        emit_copies(out, "        ", "keys", keys);
        emit_copies(out, "        ", "data", cols);
        out << "        SEND request TO DATABASE_CHANNEL;\n";
        out << "    }\n";
        out << "    COMMAND delete {\n";
        out << "        request := delete_template;\n";
        emit_copies(out, "        ", "keys", keys);
        out << "        SEND request TO DATABASE_CHANNEL;\n";
        out << "    }\n";
    }
    out << "    COMMAND find {\n";
    out << "        request := find_template;\n";
    emit_copies(out, "        ", "keys", keys);
    out << "        SEND request TO DATABASE_CHANNEL;\n";
    out << "    }\n";
    out << "    COMMAND load {\n";
    out << "        request := list_template;\n";
    out << "        SEND request TO DATABASE_CHANNEL;\n";
    out << "    }\n";
    out << "    COMMAND list {\n";
    out << "        CLEAR items;\n";
    out << "        COPY ALL FROM " << mc->name << " TO items;\n";
    out << "    }\n";
    out << "}\n";
}

} // namespace

int main(int argc, char const *argv[]) {
    char *pn = strdup(argv[0]);
    program_name = strdup(basename(pn));
    free(pn);

    const char *from = 0;
    const char *out_dir = 0;
    bool emit_schema = false;
    for (int i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "--from") == 0 && i + 1 < argc) {
            from = argv[++i];
        }
        else if (strcmp(argv[i], "--out") == 0 && i + 1 < argc) {
            out_dir = argv[++i];
        }
        else if (strcmp(argv[i], "--sql") == 0) {
            emit_schema = true;
        }
        else if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            std::cerr << "Usage: cw-scaffold --from file.cw [--out dir] [--sql]\n";
            return 0;
        }
        else {
            std::cerr << "Unknown argument: " << argv[i] << "\n";
            return 2;
        }
    }
    if (!from) {
        std::cerr << "cw-scaffold: --from is required\n";
        return 2;
    }

    zmq::context_t *context = new zmq::context_t;
    MessagingInterface::setContext(context);
    Logger::instance();
    MessageLog::setMaxMemory(10000);
    boost::condition_variable_any cond;
    boost::shared_mutex mutex;
    SharedThreadSafeQueue<Package *> queue(cond, mutex);
    Dispatcher::create(queue);
    Scheduler::instance();

    set_parse_only(1);
    std::list<std::string> files;
    files.push_back(from);
    int rc = loadConfig(files);
    if (rc) {
        return rc;
    }

    int n = 0;
    std::list<MachineClass *>::const_iterator it = MachineClass::all_machine_classes.begin();
    while (it != MachineClass::all_machine_classes.end()) {
        MachineClass *mc = *it++;
        if (!mc || !mc->is_record) {
            continue;
        }
        ++n;
        std::string generated;
        {
            std::ostringstream oss;
            emit_interface(oss, mc);
            generated = oss.str();
        }
        if (out_dir) {
            boost::filesystem::create_directories(out_dir);
            std::string path = std::string(out_dir) + "/" + mc->name + "INTERFACE.lpc";
            std::ofstream ofs(path.c_str());
            if (!ofs) {
                std::cerr << "cw-scaffold: cannot write " << path << "\n";
                return 1;
            }
            ofs << generated;
            if (emit_schema) {
                std::string spath = std::string(out_dir) + "/" + mc->name + ".sql";
                std::ofstream sfs(spath.c_str());
                if (!sfs) {
                    std::cerr << "cw-scaffold: cannot write " << spath << "\n";
                    return 1;
                }
                emit_sql(sfs, mc);
            }
        }
        else {
            std::cout << generated;
            if (emit_schema) {
                emit_sql(std::cout, mc);
            }
        }
    }
    if (n == 0) {
        std::cerr << "cw-scaffold: no RECORD classes in " << from << "\n";
        return 2;
    }
    return 0;
}
